CREATE DATABASE FreshMuffinDriver;

USE FreshMuffinDriver;

DROP TABLE IF EXISTS `client`;

CREATE TABLE driver (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  yubi_key_id VARCHAR(100) NOT NULL UNIQUE,
  user_id VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE route (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  stops VARCHAR(100) NOT NULL,
  eta VARCHAR(100) NOT NULL,
  user_id INT FOREIGN KEY REFERENCES driver(UserId)
)
